# Generated by Django 4.2.6 on 2023-11-16 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bankapi',
            new_name='Bank',
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('manager', 'manager'), ('cashier', 'cashier'), ('clerk', 'clerk')], max_length=50)),
                ('Bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bank')),
            ],
        ),
    ]
